#include <flecs.h>

ECS_COMPONENT_DECLARE(co_Position);
ECS_COMPONENT_DECLARE(co_Sprite);
ECS_COMPONENT_DECLARE(co_Velocity);
ECS_COMPONENT_DECLARE(co_Debug);

ECS_COMPONENT_DECLARE(si_Assets);
ECS_COMPONENT_DECLARE(si_Camera);
ECS_COMPONENT_DECLARE(si_Input);
